name: ECG-FM
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _sysroot_linux-64_curr_repodata_hack=3
  - absl-py=2.1.0
  - aom=3.6.1
  - argon2-cffi-bindings=21.2.0
  - asttokens=3.0.0
  - backcall=0.2.0
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40.0
  - blas=1.0
  - bleach=6.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cairo=1.16.0
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.8.55
  - cuda-runtime=12.1.0
  - cuda-version=12.8
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - expat=2.6.4
  - ffmpeg=6.1.1
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fsspec=2024.12.0
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.9
  - graphite2=1.3.14
  - grpcio=1.62.2
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=10.2.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - jsonschema=4.23.0
  - jupyter=1.1.1
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kernel-headers_linux-64=3.10.0
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarchive=3.7.7
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.13.0.11
  - libcups=2.4.2
  - libcurand=10.3.9.55
  - libcurl=8.12.1
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgl=1.7.0
  - libglib=2.78.4
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgrpc=1.62.2
  - libiconv=1.18
  - libidn2=2.3.7
  - libllvm14=14.0.6
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnghttp2=1.57.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libogg=1.3.5
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.20.0
  - libtheora=1.1.1
  - libtiff=4.2.0
  - libtorch=2.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.48.0
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - llvm-openmp=15.0.7
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mysql=8.4.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.1
  - notebook-shim=0.2.4
  - numba=0.60.0
  - numpy=1.23.5
  - numpy-base=1.23.5
  - ocl-icd=2.3.2
  - opencl-headers=2024.10.24
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openldap=2.6.4
  - openssl=3.4.1
  - opentelemetry-api=1.30.0
  - p11-kit=0.24.1
  - packaging=24.2
  - pandoc=2.12
  - parso=0.8.4
  - pcre2=10.42
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pixman=0.40.0
  - prometheus_client=0.21.0
  - prompt_toolkit=3.0.43
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycparser=2.22
  - pynndescent=0.5.10
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - qtbase=6.7.3
  - qtconsole=5.6.1
  - qtdeclarative=6.7.3
  - qtpy=2.4.1
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - re2=2022.04.01
  - readline=8.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - setuptools=75.3.0
  - sip=6.10.0
  - sleef=3.5.1
  - sqlite=3.45.3
  - stack_data=0.2.0
  - svt-av1=1.4.1
  - sysroot_linux-64=2.17
  - tbb=2021.8.0
  - tensorboard=2.19.0
  - tensorboard-data-server=0.7.0
  - tesseract=5.2.0
  - tinycss2=1.4.0
  - tk=8.6.14
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - umap-learn=0.5.4
  - urllib3=2.2.3
  - wayland=1.23.1
  - wayland-protocols=1.41
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - wrapt=1.17.0
  - x264=1!164.3095
  - x265=3.5
  - xcb-util-cursor=0.1.4
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.15
      - aiosignal==1.3.2
      - anyio==4.9.0
      - argon2-cffi==23.1.0
      - arrow==1.3.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.13
      - decorator==5.2.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fire==0.7.0
      - fonttools==4.56.0
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - h5py==3.13.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.30.1
      - importlib-resources==6.5.2
      - ipython==8.18.1
      - isoduration==20.11.0
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema-specifications==2024.10.1
      - jupyter-lsp==2.2.5
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.6
      - kiwisolver==1.4.7
      - lightning==2.5.1
      - lightning-utilities==0.14.2
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - multidict==6.3.0
      - notebook==7.3.3
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - openpyxl==3.1.5
      - overrides==7.7.0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - pexpect==4.9.0
      - pip==25.0.1
      - platformdirs==4.3.7
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.3.1
      - protobuf==6.30.2
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-json-logger==3.3.0
      - pytorch-lightning==2.5.1
      - pytz==2025.2
      - pyzmq==26.3.0
      - referencing==0.36.2
      - regex==2024.11.6
      - rpds-py==0.24.0
      - safetensors==0.5.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - statannotations==0.7.2
      - sympy==1.13.1
      - tensorboardx==2.6.2.2
      - termcolor==3.0.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.6.0+cu126
      - torchaudio==2.6.0+cu126
      - torchinfo==1.8.0
      - torchmetrics==1.7.0
      - torchvision==0.21.0+cu126
      - transformers==4.49.0
      - triton==3.2.0
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2025.2
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - yarl==1.18.3
prefix: /home/ch265498/anaconda3/envs/ECG-FM
